install:
    - sudo apt-get install -y linux-image-virtual kernel linux-image-extra-virtual
    - curl -sSL https://get.docker.com/ | sudo sh
    - sudo pip install docker-compose
    - docker-compose up -d
    - docker-compose ps
    - sleep 10

    # Setup qgis and enable the plugin
    - docker-compose exec qgis-testing-environment sh -c "qgis_setup.sh geoserverexplorer"

    # If needd additional steps (for example make or paver setup, place it here)
    # Build the GeoServer plugin
    - docker-compose exec qgis-testing-environment sh -c "pip install paver"
    - docker-compose exec qgis-testing-environment sh -c "cd /tests_directory && paver setup"

    # Link the plugin to the python/plugins directory
    - docke-composer exec -it qgis-testing-environment sh -c "ln -s /tests_directory/geoserverexplorer /root/.qgis2/python/plugins/geoserverexplorer"

before_script:
    - GEOSERVER_HOME=/usr/share/geoserver/geoserver-2.9-RC1 /usr/share/geoserver/geoserver-2.9-RC1/bin/startup.sh&
    # Wait for GS to start
    - sleep 20
script:
    # Start the real tests!
    - docker exec -it qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.catalogtests"
    - docker exec -it qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.deletetests"
    - docker exec -it qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.dragdroptests"
    - docker exec -it qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.guitests"
    # Not a real unit test?
    # - docker exec -it qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.integrationtests"

    # PKI tests
    - docker exec -it qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.pkicatalogtests"
    - docker exec -it qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.pkideletetests"
    - docker exec -it qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.pkidragdroptests"
    - docker exec -it qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.pkiguitests"
    - docker exec -it qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.pkiowstests"
